### ISSUE TITLE
specify the aspects of openness

### ISSUE THREAD

**Issue by nobodxbodon** [opencompany/awesome-open-company#25]
In the list of open companies, it's not obvious whether/how they are more than just based on OSS. For example, Buffer has metrics here: https://buffer.baremetrics.com/dashboard. Do you think it's worthwhile to create some dimensions like 'Open finance' now, and maybe 'Open Operation' in the future, with corresponding links? The list will become a table.

**Comment by waldyrious** [comment]
What do you think of [this](https://github.com/opencompany/awesome-open-company/wiki/Inclusion%20guidelines) and [this](https://github.com/opencompany/awesome-open-company#what-is-an-open-company)?

**Comment by nobodxbodon** [comment]
Yes I was thinking about making the criteria they met more explicit, like:

Company | Open Product | Open Finance | Statement | Open Standards | Open Channel
------------ | ------------- | ------------- | ------------- | ------------- | -------------
![Aleph Objects](http://www.google.com/s2/favicons?domain=alephobjects.com)[**Aleph Objects**](https://www.alephobjects.com/) | ? |  |  |  | 
![Buffer](http://www.google.com/s2/favicons?domain=buffer.com) [**Buffer**](https://buffer.com/transparency) | ? | https://buffer.baremetrics.com/dashboard | *("[Why we have a core value of transparency at our startup](http://joel.is/why-we-have-a-core-value-of-transparency-at-our-startup/)")* |  |  |

**Comment by waldyrious** [comment]
Oh, got it! Yes, I like that idea, but maybe we could use an icon system to make the list easier to read. Something similar to the approach used here: https://github.com/templeman/awesome-ipsum#legend

Do you think that could work for us?

**Comment by nobodxbodon** [comment]
Icons are surely more appealing, but finding appropriate icons might not be so easy.

**Comment by waldyrious** [comment]
Sure, I wondered the same thing. Well, we can always start with a table and switch to icons later. Feel free to propose a PR :+1:
