### ISSUE TITLE
Add link to this repo to relevant Wikipedia articles

### ISSUE THREAD

**Issue by waldyrious** [opencompany/awesome-open-company#28]
https://en.wikipedia.org/wiki/Open_business, possibly others.

As discussed in #27.

**Comment by nobodxbodon** [comment]
I just added the link to the wiki page above.

**Comment by Marzal** [comment]
I think this issue could be closed :)

**Comment by waldyrious** [comment]
Thanks for the heads-up, @Marzal. I agree, closing.
