### ISSUE TITLE
Add LightTable

### ISSUE THREAD

**Issue by waldyrious** [opencompany/awesome-open-company#3]
It's missing a page on the website explaining its commitment to openness/transparency principles. (see the [guidelines](../wiki/Inclusion-guidelines)). There's a [blog post](http://lighttable.com/2014/01/07/light-table-is-open-source/) which goes into this, but it's [buried in the archives](http://lighttable.com/archive/) rather than featured as one of the pages directly reachable from the [site's navigation](http://lighttable.com/).

Pinging @LightTable (hope this works) for feedback.

**Comment by waldyrious** [comment]
Looks like at-mentioning organizations doesn't notify the members. Since the organization only has 5 members, I hope it isn't considered spamming to mention them all: @cldwalker @ibdknox @jamii @joshuafcole @one-more-minute

I'd love to hear your feedback, guys!

**Comment by nobodxbodon** [comment]
The latest blog is [New year, same old plans](http://lighttable.com/2019/03/31/New-year-old-plans/) in 2019.
