### ISSUE TITLE
Add New Vector

### ISSUE THREAD

**Issue by waldyrious** [opencompany/awesome-open-company#41]
https://github.com/vector-im

https://vector.im/ (single-page website)

> #### Work in the open
> Almost all of the software written at New Vector is open source. Everything you do will be out in the open, you will be supported not only by your colleagues, but also by a huge community just as passionate about the project as you are.

> #### What is Matrix.org?
> Matrix is an open network for secure decentralized communication. Matrix.org publishes the open specification of the protocol, as well as open source reference servers, client SDKs, bridges, etc.
> #### What is Riot.im?
> Riot is a flagship client for the Matrix network, focusing on collaboration for teams and communities and showcasing Matrix's end-to-end encryption. Available on Web, Desktop, iOS & Android, Riot is entirely open source.
> #### Who are New Vector?
> New Vector is a for-profit startup that builds Riot as well as employing many of the core Matrix.org team. New Vector exists to grow and support the Matrix ecosystem.
> #### How does New Vector make money?
> New Vector makes money through providing paid Matrix hosting and services (coming soon!) as well as consultancy services to those building on Matrix.

> #### How can I learn more about working at New Vector?
> Since almost everything we do is open source on Github (matrix-org and vector.im) you can get a good feel for exactly what it would be like to work on these projects. Similarly joining dev-centric channels such as #matrix-dev:matrix.org provides a window into the core team and the community. Come and say hi!

Additional background, from the [Matrix.org FAQ](https://matrix.org/docs/guides/faq.html#who-is-funding-matrixorg):

> #### Who is funding Matrix.org?
> [...]
>
> For the first three years of Matrix’s development (2014-2017), most of the core contributors worked for Amdocs, who paid for them to work fulltime on Matrix. In July 2017, Amdocs considered the project to be sufficiently successful that it could now self-support and so stopped funding. The majority of the core team is now employed by New Vector, an independent company set up to hire the team and support Matrix’s development. Other contributors are funded by their own employers or donate their own time to the project.

**Comment by waldyrious** [comment]
/cc the (publicly viewable) members of the github organization: @ara4n, @bmarty, @dbkr, @erikjohnston, @jcgruenhage, @lampholder, @manuroe, @turt2live, @uhoreg.

Nothing is expected of you, by the way; I plan to add the entry to the list myself shortly. In the meantime, we'd love to hear your thoughts about this project!

**Comment by benparsons** [comment]
Hi @waldyrious,

(n.b. I just made myself public on that org, I did not realise I wasn't)

Thank you for thinking of us as an addition for your list.

Might be worth including our other GitHub organisation: https://github.com/matrix-org. We keep the pure matrix-related work separate from https://github.com/vector-im, which is used for New Vector specific work, such as Riot.

One last thing, to clarify that Matrix is a broadly used protocol of which Riot is simply the most established and adopted client, perhaps include a link to https://matrix.org/docs/projects/try-matrix-now.html, where we collect software which incorporates the protocol.

All the information about New Vector itself is fair and correct though, so thank you again for choosing to include us!

**Comment by waldyrious** [comment]
Hi Ben, thanks for the feedback.

This list is actually focused on companies, i.e. for-profit organizations, with the goal to highlight commercial business models that embrace openness in ways that challenge the common beliefs that success in a corporate environment requires secrecy, zero-sum competition or primarily extrinsic motivators.

If we were to include non-profits or organizations/projects like Matrix.org, the list would become too long to be interesting, and would lose the focus that gives it its value. I hope that makes sense to you!

ps - in the interests of keeping the git graph readable, I'll wait until #43 is merged before opening a new one adding New Vector.

**Comment by benparsons** [comment]
@waldyrious that's fine, just wanted to make the New Vector/Matrix relationship clear.

**Comment by ara4n** [comment]
thanks :)
