### ISSUE TITLE
Add ProtonMail

### ISSUE THREAD

**Issue by tomaspapi** [opencompany/awesome-open-company#47]
I think ProtonMail is qualified and meets the criteria I've seen on the readme.

- **Website:** https://protonmail.com
- **Openness Pledge:** https://protonmail.com/security-details
- **Open Product:** https://github.com/ProtonMail/WebClient / https://github.com/openpgpjs/openpgpjs
- **Statement:** https://protonmail.com/blog/protonmail-open-source-crytography/
- **Open Finance:** n/a

What do you guys think? There are many other relevant links as well to support this nomination but tried to only post the ones that are the closest match to each one of these categories. Cheers.

**Comment by waldyrious** [comment]
Hey @tomaspapi thanks for the suggestion! I agree that this would be a nice addition. Would you like to submit a PR?

**Comment by waldyrious** [comment]
Just one suggestion: I'd move the link you used as the statement to the "openness pledge" field, and use this one as the statement instead: https://protonmail.com/blog/protonmail-open-source/. What do you think?

**Comment by tomaspapi** [comment]
Hey @waldyrious — thanks for the feedback! I thought about that as well but since the link currently in Statement is a blog post, I wasn't sure if it would be a good fit for Openness Pledge.

According to the [inclusion guidelines](https://github.com/opencompany/awesome-open-company/wiki/Inclusion+guidelines) on "commitment to openness and transparency":

> This could be an "about" page, a dedicated "openness"/"transparency" page, a "values" page, or something else along those lines, and should be easily reachable.

Taking this into consideration, would you still say it's OK to make these changes? If you're in, I'm in. Thank you!

**Comment by waldyrious** [comment]
Good point. My concern was more about the content of the pages. It's kind of a conundrum in this case because the appropriate content is in a blog page, and the easily reachable content is not that adequate according to the guidelines.

I'll mull this over a bit and get back to you later.

**Comment by tomaspapi** [comment]
Sure thing. Let me know! Cheers.

**Comment by waldyrious** [comment]
@tomaspapi the website's footer has a link "Open Source" under the "Company" heading. It points to https://protonmail.com/blog/openpgpjs-3-release/, which states:

> ProtonMail is committed to open source, and all the code for OpenPGPjs can be found on [Github](https://github.com/openpgpjs/openpgpjs).

At the bottom of that post there's also the following:

> Your support allows us to continue to develop ProtonMail as free and [open source software](https://protonmail.com/blog/protonmail-open-source/).

That link is precisely https://protonmail.com/blog/protonmail-open-source/, the one I suggested above.

So either https://protonmail.com/blog/openpgpjs-3-release/, which is accessible with one click from the home page, or https://protonmail.com/blog/protonmail-open-source/, which is accessible in two clicks, would fit the reachability requirements for the openness pledge. Both are better than https://protonmail.com/security-details IMO.

If you agree, feel free to open a PR anytime :)

**Comment by tomaspapi** [comment]
Yo @waldyrious. I do agree, I'd rather go ahead with https://protonmail.com/blog/protonmail-open-source/. I'm opening the PR then. Thanks for the help and the feedback!
