### ISSUE TITLE
Aleph Objects products

### ISSUE THREAD

**Issue by FruityWelsh** [opencompany/awesome-open-company#53]
Would it make sense to add the Lulzbot to an open product made by Aleph Objects? The printers 100% FOSH.

**Comment by waldyrious** [comment]
Sounds good to me, @FruityWelsh! Feel free to send a PR at your convenience.

**Comment by FruityWelsh** [comment]
Aleph Objects is on the list now!

**Comment by waldyrious** [comment]
Aleph Objects has been on the list [since 2015](https://github.com/opencompany/awesome-open-company/pull/12) :) The Lulzbot is not in the Open Product column of that entry, though. Am I missing something?
