### ISSUE TITLE
Sentry changed to non-free license

### ISSUE THREAD

**Issue by mar-v-in** [opencompany/awesome-open-company#58]
Sentry changed to the non-free, GPL-incompatible, "Business Software License", see https://blog.sentry.io/2019/11/06/relicensing-sentry
It thus shouldn't act as an example of awesomely open.

**Comment by marclaporte** [comment]
@mar-v-in Please make a merge request on https://github.com/opencompany/awesome-open-company/blob/master/README.md with your proposed change.

**Comment by nobodxbodon** [comment]
Please see advice above.
IMHO I've not seen conflicts between the relicensing and being open to some extent.

**Comment by marclaporte** [comment]
This page says Open Source: https://github.com/opencompany/awesome-open-company?tab=readme-ov-file#what-is-an-open-company

Open Source is defined here: https://opensource.org/osd

Sentry's software is not Open Source. It is source available. There is an initiative to brand as fair source: https://github.com/fairsource/fair.io

**Comment by nobodxbodon** [comment]
> Sentry's software is not Open Source.

May I ask which item in the definition is not met?

**Comment by marclaporte** [comment]
6. No Discrimination Against Fields of Endeavor
https://opensource.org/osd

**Comment by nobodxbodon** [comment]
> Anyone should be able to run Sentry for themselves or their business

According to the post, this one of their goals is satisfied after relicensing.

**Comment by marclaporte** [comment]
> > Anyone should be able to run Sentry for themselves or their business
> 
> According to the post, this one of their goals is satisfied after relicensing.

It depends what your business does as there are restrictions. The Open Source Definition is very clear and Sentry itself rightly and clearly indicates that it's not Open Source.

https://glitchtip.com/ is an alternative to Sentry that uses the same APIs and is Open Source (https://gitlab.com/glitchtip/glitchtip-backend: license MIT). I highly recommend them.

https://github.com/opencompany/awesome-open-company is not specifically about Open Source. For example, you have Atlassian with an "Openness Pledge", while their software is proprietary (and increasingly SaaS only)

"being open to some extent" is a pretty ambiguous if used as a definition, so it's expected to have some debates :-)

Promoting interesting companies that are "open to some extent" has value. Just please don't misrepresent the very clear "Open Source" brand for software. You can use "source available" or other terms.
![2024-08-12_102926](https://github.com/user-attachments/assets/24cd4cba-f609-4c36-8f08-eeb32ad10c99)

**Comment by nobodxbodon** [comment]
Thanks for sharing the alternatives.
I've no problem to see the relicensing article listed above the current "Driven by OS" link in the table, so that viewers can judge by themselves how open Sentry is.
