### ISSUE TITLE
Are you on X/Twitter?

### ISSUE THREAD

**Issue by chadwhitacre** [opencompany/awesome-open-company#71]
@nobodxbodon Greetings! :-)

Do you have an X/Twitter account? @waldyrious and I were wondering here:

https://twitter.com/waldyrious/status/1730023367720214997

**Comment by nobodxbodon** [comment]
Hi Chad! I actually have account @WU_Xuan, but somehow I got "Your account is suspended and is not permitted to perform this action" after login. I found that a while ago and pitifully still haven't found a way to unlock it yet.

**Comment by nobodxbodon** [comment]
Hey I just got unlocked. The X support is pretty straightforward after all, "flagged as spam by mistake". AI still has a long way to go :)
